export const ROUTES = {
  tracker: "/",
  dashboard: "/dashboard",
  flowboard: "/flowboard",
  requests: "/requests",
  createRequest: "/requests/new",
  bidDetail: "/bid/:id",
  timeline: "/timeline",
  approvals: "/approvals",
  results: "/results",
  templates: "/templates",
  notifications: "/notifications",
  knowledge: "/knowledge",
  assetsCatalog: "/knowledge/assets-catalog",
  analytics: "/analytics/:view",
  reports: "/reports/:type",
  favorites: "/tools/favorites",
  quotations: "/tools/quotations",
  tooling: "/tools/tooling",
  pricing: "/tools/pricing",
  systemConfig: "/settings/config",
  members: "/settings/members",
  patchNotes: "/settings/patch-notes",
  faq: "/faq",
} as const;
